# Generated by Django 3.2.3 on 2023-09-26 12:58

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=128, unique=True, validators=[django.core.validators.MinLengthValidator(3), django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
