# Generated by Django 3.2.3 on 2023-09-28 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_recipe_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='amount',
        ),
    ]
