# Generated by Django 3.2.3 on 2023-09-28 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_remove_ingredient_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='text',
        ),
    ]
