# Generated by Django 3.2.3 on 2023-10-03 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_alter_recipe_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='self_follow_forbidden',
        ),
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique_follow',
        ),
    ]
